### ISSUE TITLE
`@null` displaying on the profile page when no Twitter Handle is present

### ISSUE THREAD

**Issue by achasveachas** [benhayehudi/aliyahgeeks#4]
On the User profile page if the user doesn't have a twitter handle the page displays @null that links to twitter.com/null

![image](https://user-images.githubusercontent.com/18297915/38033085-278f4f2a-326d-11e8-8b12-37d7fd8a5e96.png)

**Comment by hummusonrails** [comment]
Thanks for this also. This will be also addressed in the next commit.
