### ISSUE TITLE
When not logged in the card still displays a link to the user dashboard which leads to a `page not found`

### ISSUE THREAD

**Issue by achasveachas** [benhayehudi/aliyahgeeks#6]
![image](https://user-images.githubusercontent.com/18297915/38033183-75f4da54-326d-11e8-8f5b-b3a7a45c0f5a.png)

**Comment by hummusonrails** [comment]
Thanks for bringing this up. This involves a simple adjustment to the logic in the ternary operator and it will be incorporated in the next commit.
